logging:
  level: debug
  fileOutput:
    filePath: 

grpcServer:
  port: ""
  maxConcurrentStreams: 


smtpProviders:
  - name: 
    smtpHost: 
    smtpPort:
    login:
    password: 
    fromEmail: 
