// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.1
// source: proto/email-sender.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EmailSenderRequest defines the request structure for sending email.
type EmailSenderRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RecipientEmail string `protobuf:"bytes,1,opt,name=recipient_email,json=recipientEmail,proto3" json:"recipient_email,omitempty"` // Recipient's email address.
	Subject        string `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`                                     // Subject of the email.
	FromName       string `protobuf:"bytes,3,opt,name=from_name,json=fromName,proto3" json:"from_name,omitempty"`                   // Display name of the sender.
	FromEmail      string `protobuf:"bytes,4,opt,name=from_email,json=fromEmail,proto3" json:"from_email,omitempty"`                // Displayed email of the sender.
	Body           string `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`                                           // Message body.
}

func (x *EmailSenderRequest) Reset() {
	*x = EmailSenderRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_email_sender_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmailSenderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailSenderRequest) ProtoMessage() {}

func (x *EmailSenderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_email_sender_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailSenderRequest.ProtoReflect.Descriptor instead.
func (*EmailSenderRequest) Descriptor() ([]byte, []int) {
	return file_proto_email_sender_proto_rawDescGZIP(), []int{0}
}

func (x *EmailSenderRequest) GetRecipientEmail() string {
	if x != nil {
		return x.RecipientEmail
	}
	return ""
}

func (x *EmailSenderRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *EmailSenderRequest) GetFromName() string {
	if x != nil {
		return x.FromName
	}
	return ""
}

func (x *EmailSenderRequest) GetFromEmail() string {
	if x != nil {
		return x.FromEmail
	}
	return ""
}

func (x *EmailSenderRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

// EmailSenderResponse defines the structure of the response after an attempt to send an email.
type EmailSenderResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // Indicates whether the send operation was successful.
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`  // Error message or submission status.
}

func (x *EmailSenderResponse) Reset() {
	*x = EmailSenderResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_email_sender_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmailSenderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailSenderResponse) ProtoMessage() {}

func (x *EmailSenderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_email_sender_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailSenderResponse.ProtoReflect.Descriptor instead.
func (*EmailSenderResponse) Descriptor() ([]byte, []int) {
	return file_proto_email_sender_proto_rawDescGZIP(), []int{1}
}

func (x *EmailSenderResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *EmailSenderResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_email_sender_proto protoreflect.FileDescriptor

var file_proto_email_sender_proto_rawDesc = []byte{
	0x0a, 0x18, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x2d, 0x73, 0x65,
	0x6e, 0x64, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0xa7, 0x01, 0x0a, 0x12, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x53, 0x65, 0x6e, 0x64, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x27, 0x0a, 0x0f, 0x72, 0x65, 0x63, 0x69,
	0x70, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0e, 0x72, 0x65, 0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x45, 0x6d, 0x61, 0x69,
	0x6c, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x66,
	0x72, 0x6f, 0x6d, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x66, 0x72, 0x6f, 0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x66, 0x72, 0x6f, 0x6d,
	0x5f, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x66, 0x72,
	0x6f, 0x6d, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x22, 0x49, 0x0a, 0x13, 0x45,
	0x6d, 0x61, 0x69, 0x6c, 0x53, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x54, 0x0a, 0x0e, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x53,
	0x65, 0x6e, 0x64, 0x65, 0x72, 0x41, 0x70, 0x69, 0x12, 0x42, 0x0a, 0x09, 0x53, 0x65, 0x6e, 0x64,
	0x45, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x6d,
	0x61, 0x69, 0x6c, 0x53, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x53, 0x65,
	0x6e, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x2b, 0x5a, 0x29,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x2d, 0x64, 0x65, 0x76,
	0x2d, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x2f, 0x73, 0x6d, 0x74, 0x70, 0x2d, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_proto_email_sender_proto_rawDescOnce sync.Once
	file_proto_email_sender_proto_rawDescData = file_proto_email_sender_proto_rawDesc
)

func file_proto_email_sender_proto_rawDescGZIP() []byte {
	file_proto_email_sender_proto_rawDescOnce.Do(func() {
		file_proto_email_sender_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_email_sender_proto_rawDescData)
	})
	return file_proto_email_sender_proto_rawDescData
}

var file_proto_email_sender_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_email_sender_proto_goTypes = []interface{}{
	(*EmailSenderRequest)(nil),  // 0: proto.EmailSenderRequest
	(*EmailSenderResponse)(nil), // 1: proto.EmailSenderResponse
}
var file_proto_email_sender_proto_depIdxs = []int32{
	0, // 0: proto.EmailSenderApi.SendEmail:input_type -> proto.EmailSenderRequest
	1, // 1: proto.EmailSenderApi.SendEmail:output_type -> proto.EmailSenderResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_email_sender_proto_init() }
func file_proto_email_sender_proto_init() {
	if File_proto_email_sender_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_email_sender_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmailSenderRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_email_sender_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmailSenderResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_email_sender_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_email_sender_proto_goTypes,
		DependencyIndexes: file_proto_email_sender_proto_depIdxs,
		MessageInfos:      file_proto_email_sender_proto_msgTypes,
	}.Build()
	File_proto_email_sender_proto = out.File
	file_proto_email_sender_proto_rawDesc = nil
	file_proto_email_sender_proto_goTypes = nil
	file_proto_email_sender_proto_depIdxs = nil
}
